# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('markdown', models.DecimalField(decimal_places=2, max_digits=4)),
                ('image', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
    ]
