# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20170904_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='link',
            field=models.CharField(max_length=500),
        ),
    ]
